apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
  namespace: grafana
  labels:
    type: local
    app.kubernetes.io/name: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana"
